# Generated by Django 3.1.2 on 2020-12-08 03:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chuanshanghui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='内容', null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_appendix',
            field=models.FileField(blank=True, null=True, upload_to='article_appendix', verbose_name='附件上传'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(null=True, upload_to='article_image', verbose_name='封面选择'),
        ),
    ]
