# Generated by Django 3.1.2 on 2020-12-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chuanshanghui', '0002_auto_20201208_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodslist',
            old_name='fund_for_act',
            new_name='Goods_for_act',
        ),
        migrations.AddField(
            model_name='goodslist',
            name='Goods_num',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodslist',
            name='Goods_name',
            field=models.CharField(max_length=500),
        ),
    ]
